import React, { useEffect, useState } from 'react';
import api from '../../api/axios.js';
import Modal from '../../components/Modal.jsx';
import ListCard from '../../components/ListCard.jsx';
import ListRow from '../../components/ListRow.jsx';
import { useToast } from '../../context/ToastContext.jsx';

const emptyForm = { username: '', password: '', name: '', phone: '', planId: '' };

export default function Customers() {
  const { showToast } = useToast();
  const [customers, setCustomers] = useState([]);
  const [plans, setPlans] = useState([]);
  const [search, setSearch] = useState('');
  const [status, setStatus] = useState('');
  const [error, setError] = useState('');

  // Create
  const [showCreate, setShowCreate] = useState(false);
  const [createForm, setCreateForm] = useState(emptyForm);
  const [createError, setCreateError] = useState('');
  const [creating, setCreating] = useState(false);
  const [createdResult, setCreatedResult] = useState(null);

  // Edit
  const [editing, setEditing] = useState(null);
  const [editError, setEditError] = useState('');
  const [savingEdit, setSavingEdit] = useState(false);

  // Progress
  const [progressFor, setProgressFor] = useState(null);
  const [progress, setProgress] = useState(null);
  const [progressError, setProgressError] = useState('');

  // ── Password Reset ──────────────────────────────────────────────────────────
  const [resetFor, setResetFor] = useState(null);          // customer object
  const [resetPassword, setResetPassword] = useState('');   // optional; blank = auto-generate
  const [resetting, setResetting] = useState(false);
  const [resetResult, setResetResult] = useState(null);     // { newPassword, memberName, username, isAutoGenerated }

  // ── Bulk Actions ────────────────────────────────────────────────────────────
  const [selected, setSelected] = useState(new Set());      // Set of customer._id strings
  const [bulkAction, setBulkAction] = useState('activate');
  const [bulkMessage, setBulkMessage] = useState('');
  const [applyingBulk, setApplyingBulk] = useState(false);

  // ── CSV Import ──────────────────────────────────────────────────────────────
  const [showImport, setShowImport] = useState(false);
  const [csvText, setCsvText] = useState('name,username,phone\nAlex Morgan,alex.m,555-0199\nChris Evans,chris.e,555-0188');
  const [importing, setImporting] = useState(false);
  const [importResult, setImportResult] = useState(null);

  async function handleImport(e) {
    e.preventDefault();
    if (!csvText.trim()) return;
    setImporting(true);
    try {
      const { data } = await api.post('/admin/customers/import', { csvData: csvText });
      setImportResult(data);
      await load();
      showToast(data.message, 'success');
    } catch (err) {
      showToast(err.response?.data?.message || 'Import failed.', 'error');
    } finally {
      setImporting(false);
    }
  }

  function handleFileUpload(e) {
    const file = e.target.files?.[0];
    if (!file) return;
    const reader = new FileReader();
    reader.onload = (event) => {
      setCsvText(event.target?.result || '');
    };
    reader.readAsText(file);
  }

  async function load() {
    const params = {};
    if (status) params.status = status;
    if (search) params.search = search;
    const [customersRes, plansRes] = await Promise.all([
      api.get('/admin/customers', { params }),
      api.get('/admin/plans/active'),
    ]);
    setCustomers(customersRes.data);
    setPlans(plansRes.data);
    setSelected(new Set());
  }

  useEffect(() => {
    load().catch(() => setError('Could not load customers.'));
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [status]);

  function handleSearchSubmit(e) {
    e.preventDefault();
    load().catch(() => setError('Could not load customers.'));
  }

  // ── Create ──────────────────────────────────────────────────────────────────
  async function handleCreate(e) {
    e.preventDefault();
    setCreating(true);
    setCreateError('');
    try {
      const { data } = await api.post('/admin/customers', { ...createForm, planId: createForm.planId || null });
      await load();
      if (data.generatedPassword) {
        setCreatedResult({
          name: createForm.name,
          username: createForm.username,
          generatedPassword: data.generatedPassword,
        });
        setCreateForm(emptyForm);
      } else {
        setShowCreate(false);
        setCreateForm(emptyForm);
        showToast(`${createForm.name} added successfully!`, 'success');
      }
    } catch (err) {
      const msg = err.response?.data?.message || 'Could not create customer.';
      const fieldErrors = err.response?.data?.errors;
      setCreateError(fieldErrors ? Object.values(fieldErrors).flat().join(' · ') : msg);
    } finally {
      setCreating(false);
    }
  }

  // ── Edit ────────────────────────────────────────────────────────────────────
  async function handleSaveEdit(e) {
    e.preventDefault();
    setSavingEdit(true);
    setEditError('');
    try {
      await api.put(`/admin/customers/${editing._id}`, {
        name: editing.name,
        phone: editing.phone,
        planId: editing.plan?._id || editing.plan || null,
        isActive: editing.isActive,
      });
      setEditing(null);
      await load();
      showToast('Changes saved.', 'success');
    } catch (err) {
      setEditError(err.response?.data?.message || 'Could not save changes.');
    } finally {
      setSavingEdit(false);
    }
  }

  // ── Delete ──────────────────────────────────────────────────────────────────
  async function handleDelete(customer) {
    if (!window.confirm(`Remove ${customer.name}? This deletes their login and all logged data.`)) return;
    try {
      await api.delete(`/admin/customers/${customer._id}`);
      await load();
      showToast(`${customer.name} removed.`, 'info');
    } catch (err) {
      setError(err.response?.data?.message || `Could not remove ${customer.name}.`);
      showToast('Failed to remove customer.', 'error');
    }
  }

  // ── Progress ────────────────────────────────────────────────────────────────
  async function openProgress(customer) {
    setProgressFor(customer);
    setProgress(null);
    setProgressError('');
    try {
      const { data } = await api.get(`/admin/customers/${customer._id}/progress`);
      setProgress(data);
    } catch {
      setProgressError('Could not load progress data.');
    }
  }

  // ── Password Reset ──────────────────────────────────────────────────────────
  function openReset(customer) {
    setResetFor(customer);
    setResetPassword('');
    setResetResult(null);
  }

  async function handleReset(e) {
    e.preventDefault();
    setResetting(true);
    try {
      const { data } = await api.put(`/admin/customers/${resetFor._id}/reset-password`, {
        newPassword: resetPassword || undefined,
      });
      setResetResult(data);
    } catch (err) {
      showToast(err.response?.data?.message || 'Password reset failed.', 'error');
    } finally {
      setResetting(false);
    }
  }

  // ── Bulk Actions ────────────────────────────────────────────────────────────
  function toggleSelect(id) {
    setSelected((prev) => {
      const next = new Set(prev);
      next.has(id) ? next.delete(id) : next.add(id);
      return next;
    });
  }

  function toggleSelectAll() {
    if (selected.size === customers.length) {
      setSelected(new Set());
    } else {
      setSelected(new Set(customers.map((c) => c._id)));
    }
  }

  async function handleBulkApply() {
    if (selected.size === 0) return;
    if (bulkAction === 'send-announcement' && !bulkMessage.trim()) {
      showToast('Please enter a message for the announcement.', 'warning');
      return;
    }
    setApplyingBulk(true);
    try {
      const { data } = await api.post('/admin/customers/bulk-action', {
        ids: Array.from(selected),
        action: bulkAction,
        message: bulkAction === 'send-announcement' ? bulkMessage : undefined,
      });
      showToast(data.message, 'success');
      setBulkMessage('');
      await load();
    } catch (err) {
      showToast(err.response?.data?.message || 'Bulk action failed.', 'error');
    } finally {
      setApplyingBulk(false);
    }
  }

  return (
    <div>
      {/* Header */}
      <div className="mb-8 flex items-start justify-between">
        <div>
          <h1 className="mb-1 text-2xl font-semibold text-ink">Customers</h1>
          <p className="text-sm text-steel">Add, manage and monitor everyone at your gym.</p>
        </div>
        <div className="flex items-center gap-2">
          <button onClick={() => { setShowImport(true); setImportResult(null); }} className="btn-secondary">
            <svg className="icon !h-4 !w-4"><use href="#i-clipboard" /></svg>
            Import CSV
          </button>
          <button onClick={() => setShowCreate(true)} className="btn-primary">
            <svg className="icon !h-4 !w-4"><use href="#i-plus" /></svg>
            Add customer
          </button>
        </div>
      </div>

      {/* Filters */}
      <form onSubmit={handleSearchSubmit} className="mb-4 flex flex-wrap gap-3">
        <input
          className="field-input max-w-xs"
          placeholder="Search by name…"
          value={search}
          onChange={(e) => setSearch(e.target.value)}
        />
        <select className="field-input max-w-[10rem]" value={status} onChange={(e) => setStatus(e.target.value)}>
          <option value="">All statuses</option>
          <option value="active">Active</option>
          <option value="inactive">Inactive</option>
          <option value="overdue">Overdue fees</option>
        </select>
        <button type="submit" className="btn-secondary">Search</button>
      </form>

      {/* Bulk Action Toolbar */}
      {selected.size > 0 && (
        <div className="mb-4 flex flex-wrap items-center gap-3 rounded-2xl border border-chalk/20 bg-chalk/5 px-4 py-3">
          <span className="text-sm font-semibold text-ink">{selected.size} selected</span>
          <select
            className="field-input max-w-[14rem] py-1.5 text-sm"
            value={bulkAction}
            onChange={(e) => setBulkAction(e.target.value)}
          >
            <option value="activate">Activate all</option>
            <option value="deactivate">Deactivate all</option>
            <option value="send-announcement">Send announcement</option>
          </select>
          {bulkAction === 'send-announcement' && (
            <input
              className="field-input flex-1 py-1.5 text-sm"
              placeholder="Announcement message…"
              value={bulkMessage}
              onChange={(e) => setBulkMessage(e.target.value)}
            />
          )}
          <button
            onClick={handleBulkApply}
            disabled={applyingBulk}
            className="btn-primary py-1.5 text-sm"
          >
            {applyingBulk ? 'Applying…' : 'Apply'}
          </button>
          <button
            onClick={() => setSelected(new Set())}
            className="text-xs text-steel hover:text-ink"
          >
            Clear selection
          </button>
        </div>
      )}

      {error && <div className="mb-4 text-sm text-ember-dark">{error}</div>}

      <ListCard>
        {/* Select-all header */}
        {customers.length > 0 && (
          <div className="flex items-center gap-3 border-b border-ink/5 px-4 py-2">
            <input
              type="checkbox"
              checked={selected.size === customers.length && customers.length > 0}
              onChange={toggleSelectAll}
              className="rounded"
              id="select-all-customers"
              title="Select all"
            />
            <label htmlFor="select-all-customers" className="text-xs text-steel cursor-pointer">Select all</label>
          </div>
        )}

        {customers.map((c) => (
          <div key={c._id} className="flex items-center gap-3 pr-2">
            <div className="pl-4">
              <input
                type="checkbox"
                checked={selected.has(c._id)}
                onChange={() => toggleSelect(c._id)}
                className="rounded"
              />
            </div>
            <div className="flex-1">
              <ListRow
                icon="user"
                iconBg={c.isActive ? 'bg-chalk/15 text-chalk-dark' : 'bg-ink/5'}
                title={c.name}
                subtitle={`${c.phone || 'No phone'} · ${c.plan?.planName || 'No plan'} · ${c.isActive ? 'Active' : 'Inactive'}`}
                trailing={
                  <div className="flex items-center gap-3">
                    <button onClick={() => openProgress(c)} className="text-xs font-medium text-iron hover:underline">Progress</button>
                    <button onClick={() => setEditing({ ...c })} className="text-xs font-medium text-steel hover:text-ink">Edit</button>
                    <button onClick={() => openReset(c)} className="text-xs font-medium text-chalk hover:text-chalk-dark">Reset PW</button>
                    <button onClick={() => handleDelete(c)} className="text-xs font-medium text-steel hover:text-ember-dark">Remove</button>
                  </div>
                }
              />
            </div>
          </div>
        ))}
        {customers.length === 0 && (
          <div className="px-4 py-8 text-center text-sm text-steel">No customers match this view.</div>
        )}
      </ListCard>

      {/* ── Create Modal ───────────────────────────────────────────────────── */}
      {showCreate && (
        <Modal title="Add customer" onClose={() => { setShowCreate(false); setCreatedResult(null); }}>
          {!createdResult ? (
            <form onSubmit={handleCreate}>
              <div className="mb-4">
                <label className="field-label">Full name</label>
                <input className="field-input" value={createForm.name} onChange={(e) => setCreateForm({ ...createForm, name: e.target.value })} required />
              </div>
              <div className="mb-4">
                <label className="field-label">Username</label>
                <input className="field-input" value={createForm.username} onChange={(e) => setCreateForm({ ...createForm, username: e.target.value })} required />
              </div>
              <div className="mb-4">
                <label className="field-label">
                  Temporary password <span className="font-normal text-steel">(optional — auto-generated if blank)</span>
                </label>
                <input
                  type="text"
                  className="field-input font-mono"
                  placeholder="Leave blank to auto-generate"
                  value={createForm.password}
                  onChange={(e) => setCreateForm({ ...createForm, password: e.target.value })}
                  minLength={createForm.password ? 8 : undefined}
                />
              </div>
              <div className="mb-4">
                <label className="field-label">Phone</label>
                <input className="field-input" value={createForm.phone} onChange={(e) => setCreateForm({ ...createForm, phone: e.target.value })} />
              </div>
              <div className="mb-4">
                <label className="field-label">Plan</label>
                <select className="field-input" value={createForm.planId} onChange={(e) => setCreateForm({ ...createForm, planId: e.target.value })}>
                  <option value="">No plan</option>
                  {plans.map((p) => (
                    <option key={p._id} value={p._id}>{p.planName} — ${p.price}/{p.durationMonths}mo</option>
                  ))}
                </select>
              </div>
              {createError && <div className="mb-3 rounded-xl bg-ember/10 px-3 py-2 text-sm text-ember-dark">{createError}</div>}
              <button type="submit" disabled={creating} className="btn-primary w-full">
                {creating ? 'Creating…' : 'Create customer'}
              </button>
            </form>
          ) : (
            <div className="text-center">
              <div className="mb-4 flex items-center justify-center">
                <div className="flex h-14 w-14 items-center justify-center rounded-full bg-green-500/15 text-green-500">
                  <svg viewBox="0 0 20 20" fill="currentColor" className="h-7 w-7">
                    <path fillRule="evenodd" d="M16.707 5.293a1 1 0 010 1.414l-7 7a1 1 0 01-1.414 0l-3-3a1 1 0 011.414-1.414L9 11.586l6.293-6.293a1 1 0 011.414 0z" clipRule="evenodd" />
                  </svg>
                </div>
              </div>
              <h3 className="mb-1 font-semibold text-ink">Customer Account Created</h3>
              <p className="mb-5 text-sm text-steel">
                Give these login credentials to <strong>{createdResult.name}</strong>.
              </p>

              <div className="rounded-2xl border border-ink/10 bg-ink/5 px-5 py-4 text-left">
                <div className="mb-3">
                  <div className="mb-0.5 text-xs font-semibold uppercase tracking-wide text-steel">Username</div>
                  <div className="font-mono text-base text-ink select-all">{createdResult.username}</div>
                </div>
                <div>
                  <div className="mb-0.5 text-xs font-semibold uppercase tracking-wide text-steel">
                    Auto-Generated Password
                  </div>
                  <div className="font-mono text-xl font-bold tracking-wider text-ink select-all">{createdResult.generatedPassword}</div>
                </div>
              </div>

              <p className="mt-4 text-xs text-steel">
                ⚠️ Share this password with the member. No email is required.
              </p>
              <button
                onClick={() => { setShowCreate(false); setCreatedResult(null); }}
                className="btn-primary mt-5 w-full"
              >
                Done
              </button>
            </div>
          )}
        </Modal>
      )}

      {/* ── Edit Modal ─────────────────────────────────────────────────────── */}
      {editing && (
        <Modal title={`Edit ${editing.name}`} onClose={() => setEditing(null)}>
          <form onSubmit={handleSaveEdit}>
            <div className="mb-4">
              <label className="field-label">Full name</label>
              <input className="field-input" value={editing.name} onChange={(e) => setEditing({ ...editing, name: e.target.value })} required />
            </div>
            <div className="mb-4">
              <label className="field-label">Phone</label>
              <input className="field-input" value={editing.phone || ''} onChange={(e) => setEditing({ ...editing, phone: e.target.value })} />
            </div>
            <div className="mb-4">
              <label className="field-label">Plan</label>
              <select className="field-input" value={editing.plan?._id || editing.plan || ''} onChange={(e) => setEditing({ ...editing, plan: e.target.value })}>
                <option value="">No plan</option>
                {plans.map((p) => (
                  <option key={p._id} value={p._id}>{p.planName} — ${p.price}/{p.durationMonths}mo</option>
                ))}
              </select>
            </div>
            <div className="mb-4">
              <label className="flex items-center gap-2 text-sm text-ink/80">
                <input type="checkbox" checked={editing.isActive} onChange={(e) => setEditing({ ...editing, isActive: e.target.checked })} />
                Active
              </label>
            </div>
            {editError && <div className="mb-3 rounded-xl bg-ember/10 px-3 py-2 text-sm text-ember-dark">{editError}</div>}
            <button type="submit" disabled={savingEdit} className="btn-primary w-full">
              {savingEdit ? 'Saving…' : 'Save changes'}
            </button>
          </form>
        </Modal>
      )}

      {/* ── Password Reset Modal ────────────────────────────────────────────── */}
      {resetFor && (
        <Modal title={`Reset password — ${resetFor.name}`} onClose={() => { setResetFor(null); setResetResult(null); }}>
          {!resetResult ? (
            <form onSubmit={handleReset}>
              <p className="mb-4 text-sm text-steel">
                Set a new password for <strong className="text-ink">{resetFor.name}</strong> (username: <code className="rounded bg-ink/5 px-1">{resetFor.user?.username || '—'}</code>).
                Leave blank to auto-generate a random password that you can share in person.
              </p>
              <div className="mb-4">
                <label className="field-label">
                  New password <span className="font-normal text-steel">(optional — leave blank to auto-generate)</span>
                </label>
                <input
                  type="text"
                  className="field-input font-mono"
                  placeholder="Leave blank to auto-generate"
                  value={resetPassword}
                  onChange={(e) => setResetPassword(e.target.value)}
                  minLength={resetPassword ? 8 : undefined}
                  autoComplete="off"
                />
              </div>
              <button type="submit" disabled={resetting} className="btn-primary w-full">
                {resetting ? 'Resetting…' : 'Reset password'}
              </button>
            </form>
          ) : (
            /* ── Success view: show the new password clearly ── */
            <div className="text-center">
              <div className="mb-4 flex items-center justify-center">
                <div className="flex h-14 w-14 items-center justify-center rounded-full bg-green-500/15 text-green-500">
                  <svg viewBox="0 0 20 20" fill="currentColor" className="h-7 w-7">
                    <path fillRule="evenodd" d="M16.707 5.293a1 1 0 010 1.414l-7 7a1 1 0 01-1.414 0l-3-3a1 1 0 011.414-1.414L9 11.586l6.293-6.293a1 1 0 011.414 0z" clipRule="evenodd" />
                  </svg>
                </div>
              </div>
              <h3 className="mb-1 font-semibold text-ink">Password Reset Successfully</h3>
              <p className="mb-5 text-sm text-steel">
                Share these credentials with <strong>{resetResult.memberName}</strong> in person.
              </p>

              <div className="rounded-2xl border border-ink/10 bg-ink/5 px-5 py-4 text-left">
                <div className="mb-3">
                  <div className="mb-0.5 text-xs font-semibold uppercase tracking-wide text-steel">Username</div>
                  <div className="font-mono text-base text-ink select-all">{resetResult.username}</div>
                </div>
                <div>
                  <div className="mb-0.5 text-xs font-semibold uppercase tracking-wide text-steel">
                    New password {resetResult.isAutoGenerated && <span className="text-amber-500">(auto-generated)</span>}
                  </div>
                  <div className="font-mono text-xl font-bold tracking-wider text-ink select-all">{resetResult.newPassword}</div>
                </div>
              </div>

              <p className="mt-4 text-xs text-steel">
                ⚠️ This password is only shown once. Ask the member to change it after logging in.
              </p>
              <button
                onClick={() => { setResetFor(null); setResetResult(null); }}
                className="btn-primary mt-5 w-full"
              >
                Done
              </button>
            </div>
          )}
        </Modal>
      )}

      {/* ── Progress Modal ──────────────────────────────────────────────────── */}
      {progressFor && (
        <Modal title={`${progressFor.name} — progress`} onClose={() => setProgressFor(null)} width="max-w-2xl">
          {progressError ? (
            <div className="py-8 text-center text-sm text-ember-dark">{progressError}</div>
          ) : !progress ? (
            <div className="py-8 text-center text-sm text-steel">Loading…</div>
          ) : (
            <div className="space-y-6">
              <div className="grid grid-cols-2 gap-4">
                <div className="panel px-4 py-3">
                  <div className="text-xs uppercase tracking-wide text-steel">Current streak</div>
                  <div className="stat-number mt-1 text-lg">{progress.streak?.currentStreak ?? 0} days</div>
                </div>
                <div className="panel px-4 py-3">
                  <div className="text-xs uppercase tracking-wide text-steel">Longest streak</div>
                  <div className="stat-number mt-1 text-lg">{progress.streak?.longestStreak ?? 0} days</div>
                </div>
              </div>

              <div>
                <div className="mb-2 text-sm font-medium text-steel">Recent weight</div>
                <ul className="space-y-1 text-sm text-ink/80">
                  {progress.weight.slice(0, 5).map((w) => (
                    <li key={w._id}>{new Date(w.date).toLocaleDateString()} — {w.weightKg} kg</li>
                  ))}
                  {progress.weight.length === 0 && <li className="text-steel">No entries yet.</li>}
                </ul>
              </div>

              <div>
                <div className="mb-2 text-sm font-medium text-steel">Recent workouts</div>
                <ul className="space-y-1 text-sm text-ink/80">
                  {progress.workouts.slice(0, 5).map((w) => (
                    <li key={w._id}>{new Date(w.date).toLocaleDateString()} — {w.isRestDay ? 'Rest day' : w.exercise}</li>
                  ))}
                  {progress.workouts.length === 0 && <li className="text-steel">No entries yet.</li>}
                </ul>
              </div>

              <div>
                <div className="mb-2 text-sm font-medium text-steel">Recent diet</div>
                <ul className="space-y-1 text-sm text-ink/80">
                  {progress.diet.slice(0, 5).map((d) => (
                    <li key={d._id}>{new Date(d.date).toLocaleDateString()} — {d.meal}{d.calories ? ` (${d.calories} cal)` : ''}</li>
                  ))}
                  {progress.diet.length === 0 && <li className="text-steel">No entries yet.</li>}
                </ul>
              </div>
            </div>
          )}
        </Modal>
      )}

      {/* ── CSV Import Modal ──────────────────────────────────────────────── */}
      {showImport && (
        <Modal
          title="Bulk Import Members (CSV)"
          onClose={() => { setShowImport(false); setImportResult(null); }}
        >
          {!importResult ? (
            <form onSubmit={handleImport}>
              <p className="mb-3 text-xs text-steel">
                Upload or paste member details in CSV format. Columns: <code className="rounded bg-ink/5 px-1">name,username,phone,password</code>.
                Password is <strong>optional</strong> (auto-generated if omitted). Email is not required.
              </p>

              <div className="mb-3">
                <label className="field-label">Upload .csv file (optional)</label>
                <input
                  type="file"
                  accept=".csv,.txt"
                  onChange={handleFileUpload}
                  className="field-input text-xs"
                />
              </div>

              <div className="mb-4">
                <label className="field-label">CSV Content</label>
                <textarea
                  rows={6}
                  className="field-input font-mono text-xs"
                  value={csvText}
                  onChange={(e) => setCsvText(e.target.value)}
                  placeholder="name,username,phone\nJohn Doe,john.doe,555-0100"
                  required
                />
              </div>

              <button type="submit" disabled={importing || !csvText.trim()} className="btn-primary w-full">
                {importing ? 'Importing Members…' : 'Start Import'}
              </button>
            </form>
          ) : (
            <div>
              <div className="mb-4 flex items-center gap-2 text-sm font-semibold text-chalk-dark">
                <svg className="icon !h-5 !w-5"><use href="#i-check-circle" /></svg>
                {importResult.message}
              </div>

              {importResult.created?.length > 0 && (
                <div className="mb-4 max-h-48 overflow-y-auto rounded-xl border border-ink/10 bg-ink/5 p-3 text-xs">
                  <div className="mb-2 font-semibold text-ink">Created Members & Passwords:</div>
                  {importResult.created.map((c, idx) => (
                    <div key={idx} className="flex justify-between py-1 border-b border-ink/5 last:border-0">
                      <span><strong>{c.name}</strong> ({c.username})</span>
                      <span className="font-mono text-iron select-all">{c.password}</span>
                    </div>
                  ))}
                </div>
              )}

              {importResult.skipped?.length > 0 && (
                <div className="mb-4 rounded-xl border border-ember/20 bg-ember/5 p-3 text-xs text-ember-dark">
                  <div className="mb-1 font-semibold">Skipped ({importResult.skipped.length}):</div>
                  {importResult.skipped.map((s, idx) => (
                    <div key={idx}>{s.name} ({s.username}): {s.reason}</div>
                  ))}
                </div>
              )}

              <button
                onClick={() => { setShowImport(false); setImportResult(null); }}
                className="btn-primary w-full"
              >
                Done
              </button>
            </div>
          )}
        </Modal>
      )}
    </div>
  );
}
